### ISSUE TITLE
its not installing

### ISSUE THREAD

**Issue by ayyappamalla123** [zboro/amd-navigator#1]
Installing “amd-navigator@0.1.2” failed.Hide output…

> ctags@3.0.0 install /tmp/apm-install-dir-11658-19011-1n3yzqc/node_modules/amd-navigator/node_modules/symbols-view/node_modules/ctags
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-11658-19011-1n3yzqc/node_modules/amd-navigator/node_modules/symbols-view/node_modules/ctags/build'
  CC(target) Release/obj.target/ctags/src/readtags.o
  CXX(target) Release/obj.target/ctags/src/tags.o
make: Leaving directory`/tmp/apm-install-dir-11658-19011-1n3yzqc/node_modules/amd-navigator/node_modules/symbols-view/node_modules/ctags/build'

In file included from ../src/tags.h:5:0,
                 from ../src/tags.cc:2:
../node_modules/nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /home/bitlasoft/.atom/.node-gyp/.node-gyp/0.36.8/src/node.h:42:0,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/tags.h:5,
                 from ../src/tags.cc:2:
/home/bitlasoft/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/bitlasoft/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/bitlasoft/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:856:1: error: expected unqualified-id before ‘using’
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/tags.h:5,
                 from ../src/tags.cc:2:
../node_modules/nan/nan_maybe_43_inl.h:13:1: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:16:1: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:19:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:24:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:31:1: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:36:1: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:41:1: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:46:1: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:51:1: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:59:1: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:64:8: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:69:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:76:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:83:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:91:8: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:98:1: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:108:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:114:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:118:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:125:1: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:130:1: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:135:1: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:139:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:145:8: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:150:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:156:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:162:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:168:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:174:8: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:180:8: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:186:8: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:194:8: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:201:1: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:205:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:209:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:213:8: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:217:8: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_maybe_43_inl.h:237:8: error: ‘MaybeLocal’ does not name a type
In file included from ../node_modules/nan/nan.h:195:0,
                 from ../src/tags.h:5,
                 from ../src/tags.cc:2:
../node_modules/nan/nan_converters.h:14:11: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_converters.h:16:56: error: ‘Maybe’ does not name a type
../node_modules/nan/nan_converters.h:26:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:27:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:28:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:29:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:30:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:31:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:32:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:42:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:43:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:44:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:45:1: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:46:1: error: ‘return_t’ does not name a type
In file included from ../node_modules/nan/nan_converters.h:59:0,
                 from ../node_modules/nan/nan.h:195,
                 from ../src/tags.h:5,
                 from ../src/tags.cc:2:
../node_modules/nan/nan_converters_43_inl.h:18:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactoryv8::Boolean’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:19:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactoryv8::Number’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:20:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactoryv8::String’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:21:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactoryv8::Object’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:22:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactoryv8::Integer’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:23:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactoryv8::Uint32’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:24:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactoryv8::Int32’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:34:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<bool>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:35:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<double>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:36:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<long int>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:37:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<unsigned int>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:38:1: error: ‘return_t’ in ‘struct Nan::imp::ToFactory<int>’ does not name a type
In file included from ../node_modules/nan/nan.h:196:0,
                 from ../src/tags.h:5,
                 from ../src/tags.cc:2:
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Localv8::Integer) [with T = v8::Integer]’:
../node_modules/nan/nan_new.h:21:32: error: no matching function for call to ‘To(v8::Localv8::Integer&)’
../node_modules/nan/nan_new.h:21:32: note: candidate is:
../node_modules/nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Localv8::Value)
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Localv8::Integer) [with T = v8::Int32]’:
../node_modules/nan/nan_new.h:28:30: error: no matching function for call to ‘To(v8::Localv8::Integer&)’
../node_modules/nan/nan_new.h:28:30: note: candidate is:
../node_modules/nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Localv8::Value)
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Localv8::Integer) [with T = v8::Uint32]’:
../node_modules/nan/nan_new.h:35:31: error: no matching function for call to ‘To(v8::Localv8::Integer&)’
../node_modules/nan/nan_new.h:35:31: note: candidate is:
../node_modules/nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Localv8::Value)
../node_modules/nan/nan_new.h: At global scope:
../node_modules/nan/nan_new.h:43:11: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan_new.h:75:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:141:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:147:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:148:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:160:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:161:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:162:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:163:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:165:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:166:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:182:17: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:183:17: error: ‘return_t’ does not name a type
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:196,
                 from ../src/tags.h:5,
                 from ../src/tags.cc:2:
../node_modules/nan/nan_implementation_12_inl.h:61:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::Date’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBasev8::Function::return_t Nan::imp::Factoryv8::Function::New(Nan::FunctionCallback, v8::Localv8::Value)’:
../node_modules/nan/nan_implementation_12_inl.h:95:46: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBasev8::FunctionTemplate::return_t Nan::imp::Factoryv8::FunctionTemplate::New(Nan::FunctionCallback, v8::Localv8::Value, v8::Localv8::Signature)’:
../node_modules/nan/nan_implementation_12_inl.h:123:48: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan_implementation_12_inl.h: At global scope:
../node_modules/nan/nan_implementation_12_inl.h:202:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::RegExp’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:221:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::Script’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:227:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::Script’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:259:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:267:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:273:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:280:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:286:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:291:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:352:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::UnboundScript’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:359:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::UnboundScript’ does not name a type
In file included from ../node_modules/nan/nan.h:196:0,
                 from ../src/tags.h:5,
                 from ../src/tags.cc:2:
../node_modules/nan/nan_new.h:293:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_new.h:299:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_new.h:305:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_new.h:311:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_new.h:317:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_new.h:323:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_new.h:329:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::String’ does not name a type
../node_modules/nan/nan_new.h:335:1: error: ‘return_t’ in ‘struct Nan::imp::Factoryv8::RegExp’ does not name a type
In file included from ../src/tags.h:5:0,
                 from ../src/tags.cc:2:
../node_modules/nan/nan.h: In function ‘v8::Localv8::Value Nan::Error(const char_)’:
../node_modules/nan/nan.h:655:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowError(const char_)’:
../node_modules/nan/nan.h:655:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Localv8::Value Nan::RangeError(const char_)’:
../node_modules/nan/nan.h:656:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowRangeError(const char_)’:
../node_modules/nan/nan.h:656:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Localv8::Value Nan::ReferenceError(const char_)’:
../node_modules/nan/nan.h:657:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowReferenceError(const char_)’:
../node_modules/nan/nan.h:657:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Localv8::Value Nan::SyntaxError(const char_)’:
../node_modules/nan/nan.h:658:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowSyntaxError(const char_)’:
../node_modules/nan/nan.h:658:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Localv8::Value Nan::TypeError(const char_)’:
../node_modules/nan/nan.h:659:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowTypeError(const char_)’:
../node_modules/nan/nan.h:659:3: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:667:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h:689:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h:705:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h:718:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h:735:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h:741:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h:749:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h:756:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h:762:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h: In member function ‘void Nan::Callback::SetFunction(const v8::Localv8::Function&)’:
../node_modules/nan/nan.h:1398:40: error: ‘Set’ was not declared in this scope
../node_modules/nan/nan.h:1398:40: note: suggested alternative:
/home/bitlasoft/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:3019:17: note:   ‘v8::Set’
../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char_, const v8::Localv8::Value&)’:
../node_modules/nan/nan.h:1518:41: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘v8::Localv8::Value Nan::AsyncWorker::GetFromPersistent(const char_) const’:
../node_modules/nan/nan.h:1536:45: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘virtual void Nan::AsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:1570:58: error: no matching function for call to ‘New(const char_)’
../node_modules/nan/nan.h:1570:58: note: candidates are:
../node_modules/nan/nan_implementation_12_inl.h:395:21: note: template<class T, class M> v8::Local<T> Nan::New(const v8::Persistent<S, M>&)
../node_modules/nan/nan_implementation_12_inl.h:400:21: note: template<class T, class M> v8::Local<T> Nan::New(const Nan::Persistent<T, M>&)
../node_modules/nan/nan_implementation_12_inl.h:405:21: note: template<class T> v8::Local<T> Nan::New(const Nan::Global<T>&)
../node_modules/nan/nan_new.h:201:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New()
../node_modules/nan/nan_new.h:207:1: note: template<class T, class A0> typename Nan::imp::Factory<T>::return_t Nan::New(A0)
../node_modules/nan/nan_new.h:213:1: note: template<class T, class A0, class A1> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1)
../node_modules/nan/nan_new.h:219:1: note: template<class T, class A0, class A1, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2)
../node_modules/nan/nan_new.h:225:1: note: template<class T, class A0, class A1, class A2, class A3> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2, A3)
../node_modules/nan/nan_new.h:237:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New(Nan::FunctionCallback, v8::Localv8::Value)
../node_modules/nan/nan_new.h:245:1: note: template<class T, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(Nan::FunctionCallback, v8::Localv8::Value, A2)
../node_modules/nan/nan.h: In function ‘void Nan::imp::SetMethodAux(T, v8::Localv8::String, v8::Localv8::FunctionTemplate, ...)’:
../node_modules/nan/nan.h:1872:34: error: there are no arguments to ‘GetFunction’ that depend on a template parameter, so a declaration of ‘GetFunction’ must be available [-fpermissive]
../node_modules/nan/nan.h:1872:34: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../node_modules/nan/nan.h: In function ‘void Nan::SetMethod(HandleType<T>, const char_, Nan::FunctionCallback)’:
../node_modules/nan/nan.h:1884:45: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::SetPrototypeMethod(v8::Localv8::FunctionTemplate, const char_, Nan::FunctionCallback)’:
../node_modules/nan/nan.h:1899:45: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::SetAccessor(v8::Localv8::ObjectTemplate, v8::Localv8::String, Nan::GetterCallback, Nan::SetterCallback, v8::Localv8::Value, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:
../node_modules/nan/nan.h:1924:47: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Localv8::Object, v8::Localv8::String, Nan::GetterCallback, Nan::SetterCallback, v8::Localv8::Value, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1967:51: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan.h: In function ‘void Nan::SetNamedPropertyHandler(v8::Localv8::ObjectTemplate, Nan::PropertyGetterCallback, Nan::PropertySetterCallback, Nan::PropertyQueryCallback, Nan::PropertyDeleterCallback, Nan::PropertyEnumeratorCallback, v8::Localv8::Value)’:
../node_modules/nan/nan.h:2026:47: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan.h: In function ‘void Nan::SetIndexedPropertyHandler(v8::Localv8::ObjectTemplate, Nan::IndexGetterCallback, Nan::IndexSetterCallback, Nan::IndexQueryCallback, Nan::IndexDeleterCallback, Nan::IndexEnumeratorCallback, v8::Localv8::Value)’:
../node_modules/nan/nan.h:2096:47: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan.h: In function ‘void Nan::SetCallHandler(v8::Localv8::FunctionTemplate, Nan::FunctionCallback, v8::Localv8::Value)’:
../node_modules/nan/nan.h:2151:47: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan.h: In function ‘void Nan::SetCallAsFunctionHandler(v8::Localv8::ObjectTemplate, Nan::FunctionCallback, v8::Localv8::Value)’:
../node_modules/nan/nan.h:2173:47: error: ‘NewInstance’ was not declared in this scope
In file included from ../src/tags.h:5:0,
                 from ../src/tags.cc:2:
../node_modules/nan/nan.h: In function ‘void Nan::Export(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE, const char_, Nan::FunctionCallback)’:
../node_modules/nan/nan.h:2200:35: error: no matching function for call to ‘New(const char_&)’
../node_modules/nan/nan.h:2200:35: note: candidates are:
../node_modules/nan/nan_implementation_12_inl.h:395:21: note: template<class T, class M> v8::Local<T> Nan::New(const v8::Persistent<S, M>&)
../node_modules/nan/nan_implementation_12_inl.h:400:21: note: template<class T, class M> v8::Local<T> Nan::New(const Nan::Persistent<T, M>&)
../node_modules/nan/nan_implementation_12_inl.h:405:21: note: template<class T> v8::Local<T> Nan::New(const Nan::Global<T>&)
../node_modules/nan/nan_new.h:201:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New()
../node_modules/nan/nan_new.h:207:1: note: template<class T, class A0> typename Nan::imp::Factory<T>::return_t Nan::New(A0)
../node_modules/nan/nan_new.h:213:1: note: template<class T, class A0, class A1> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1)
../node_modules/nan/nan_new.h:219:1: note: template<class T, class A0, class A1, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2)
../node_modules/nan/nan_new.h:225:1: note: template<class T, class A0, class A1, class A2, class A3> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2, A3)
../node_modules/nan/nan_new.h:237:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New(Nan::FunctionCallback, v8::Localv8::Value)
../node_modules/nan/nan_new.h:245:1: note: template<class T, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(Nan::FunctionCallback, v8::Localv8::Value, A2)
../node_modules/nan/nan.h:2201:47: error: ‘GetFunction’ was not declared in this scope
../node_modules/nan/nan.h:2201:65: error: ‘Set’ was not declared in this scope
../node_modules/nan/nan.h:2201:65: note: suggested alternative:
/home/bitlasoft/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:3019:17: note:   ‘v8::Set’
../node_modules/nan/nan.h: In constructor ‘Nan::Tap::Tap(v8::Localv8::Value)’:
../node_modules/nan/nan.h:2208:30: error: no matching function for call to ‘To(v8::Localv8::Value&)’
../node_modules/nan/nan.h:2208:30: note: candidate is:
../node_modules/nan/nan_converters.h:53:38: note: template<class T> typename Nan::imp::ToFactory::return_t Nan::To(v8::Localv8::Value)
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::ok(bool, const char_)’:
../node_modules/nan/nan.h:2221:33: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::pass(const char_)’:
../node_modules/nan/nan.h:2227:30: error: ‘Nan::imp::FactoryBasev8::Boolean::return_t’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:2251:10: error: ‘MaybeLocal’ does not name a type
../node_modules/nan/nan.h:2256:40: error: ‘MaybeLocal’ was not declared in this scope
../node_modules/nan/nan.h:2256:40: note: suggested alternative:
/home/bitlasoft/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:111:7: note:   ‘v8::MaybeLocal’
../node_modules/nan/nan.h:2256:52: error: template argument 1 is invalid
../node_modules/nan/nan.h:2256:54: error: expected unqualified-id before ‘>’ token
../node_modules/nan/nan.h:2265:1: error: ‘MaybeLocal’ does not name a type
In file included from ../src/tags.cc:2:0:
../src/tags.h:12:20: error: ‘Handle’ has not been declared
../src/tags.h:12:26: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/tags.h:23:23: error: expected ‘)’ before ‘<’ token
../src/tags.cc:6:17: error: variable or field ‘Init’ declared void
../src/tags.cc:6:17: error: ‘Handle’ was not declared in this scope
../src/tags.cc:6:30: error: expected primary-expression before ‘>’ token
../src/tags.cc:6:32: error: ‘target’ was not declared in this scope
../src/tags.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Tags::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/tags.cc:26:53: error: no matching function for call to ‘Tags::Tags(v8::Localv8::String)’
../src/tags.cc:26:53: note: candidates are:
../src/tags.h:10:7: note: Tags::Tags()
../src/tags.h:10:7: note:   candidate expects 0 arguments, 1 provided
../src/tags.h:10:7: note: Tags::Tags(const Tags&)
../src/tags.h:10:7: note:   no known conversion for argument 1 from ‘v8::Localv8::String’ to ‘const Tags&’
../src/tags.cc: At global scope:
../src/tags.cc:64:11: error: expected constructor, destructor, or type conversion before ‘(’ token
make: *_\* [Release/obj.target/ctags/src/tags.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.5.0-54-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11658-19011-1n3yzqc/node_modules/amd-navigator/node_modules/symbols-view/node_modules/ctags
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.5.0-54-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/bitlasoft/.atom/.apm/.apmrc" "--userconfig" "/home/bitlasoft/.atom/.apmrc" "install" "/tmp/d-11658-19011-1u41lpt/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! ctags@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11658-19011-1n3yzqc/npm-debug.log

**Comment by zboro** [comment]
I just tried reinstalling it and it works for me. I used Ubuntu 16.04, node 4.2, npm 3.5, atom 1.8.
